# Generated by Django 5.0.4 on 2024-04-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_notes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
