# Generated by Django 5.0.4 on 2024-04-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_notes_folder_id_alter_folders_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='folder_id',
            new_name='folder',
        ),
    ]
