# Generated by Django 5.0.4 on 2024-04-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_rename_folder_id_notes_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
