# Generated by Django 5.0.4 on 2024-04-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_folders_is_deleted_notes_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folders',
            name='is_deleted',
        ),
    ]
