# Generated by Django 5.0.4 on 2024-04-30 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0012_remove_folders_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='folder',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='note.folders'),
        ),
    ]
