# Generated by Django 5.0.4 on 2024-04-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
