# Generated by Django 5.0.4 on 2024-04-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_alter_notes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='main_folder',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
