# Generated by Django 5.0.4 on 2024-05-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0013_alter_notes_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='subfolder',
            field=models.TextField(default=0),
        ),
    ]
