# Generated by Django 5.0.4 on 2024-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0020_rename_subfolder_folders_parent_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='there_subfolders',
            field=models.BooleanField(default=False),
        ),
    ]
