# Generated by Django 5.0.4 on 2024-05-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0021_folders_there_subfolders'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='subfolder_level',
            field=models.TextField(default='0'),
        ),
    ]
