# Generated by Django 5.0.4 on 2024-06-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0022_folders_subfolder_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
