# Generated by Django 5.0.4 on 2024-06-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0024_folders_user_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folders',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='slug',
        ),
    ]
